services:
  - type: web
    name: barcode-extractor
    env: python
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: uvicorn server.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
